# Generated by Django 3.1.6 on 2022-08-16 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Team Name', max_length=25)),
                ('age_range', models.CharField(blank=True, help_text='Team Age Range', max_length=20)),
                ('location', models.CharField(help_text='Team Locatiion', max_length=40)),
                ('level', models.IntegerField(help_text='Team Level')),
            ],
            options={
                'ordering': ['name', 'level'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User Full Name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='User Age')),
                ('position', models.CharField(help_text='User Position', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date time')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date time')),
            ],
            options={
                'ordering': ['name', 'age'],
            },
        ),
    ]
