# Generated by Django 4.0.6 on 2022-08-13 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User Full Name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='User Age')),
                ('position', models.CharField(help_text='User Position', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date time')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date time')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
