# Generated by Django 3.1.6 on 2022-08-16 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Stadium Name', max_length=30)),
                ('date', models.CharField(help_text='Match date and time', max_length=22)),
                ('level', models.IntegerField(help_text='Match Level')),
                ('limitation', models.IntegerField(help_text='Limitation for the personnel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
