# Generated by Django 3.1.6 on 2022-08-15 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Team Name', max_length=255)),
                ('age_range', models.CharField(blank=True, help_text='Team Age Range', max_length=20)),
                ('location', models.CharField(help_text='Team Locatiion', max_length=40)),
                ('level', models.IntegerField(help_text='Team Level')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['name', 'age'], 'verbose_name': '유저 정보', 'verbose_name_plural': '유저 정보'},
        ),
    ]
